version: "3"

services:

  web:
    # build from Dockerfile
    build: .
    # docker-compose run --rm --service-ports web
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=setcain
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - db_data:/var/lib/postgres/data/pgdata

volumes:
  db_data:
